spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cl-token
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 63871
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect