server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_reg
    username: root
    password: 63871
    driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
